### PR TITLE
Fix indexer fails with `system.set_code()` extrinsic 

### PR DESCRIPTION
**Pull request by dastanbeksamatov**
## Issue
While using `indexer` for `Polkadot` and `Kusama` chains, it fails to decode&index several blocks. The block numbers are: `polkadot` - 1603423, 2005673, 2436698 and in `kusama` - 2064961, 2201991, 2671528. Examples of error messages:

```
error: 2005673-unknown createType(Vec<EventRecord>):: decodeU8a: failed at 0x02090c7b4fcd4c00… on : 
{"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x090c7b4fcd4c0041… on event: <br/>     {"index":"EventId","data":"Null"}:: findMetaEvent: Unable to find Event with index 0x090c/[9,12] {"stack":"Error: \<br/>   
  createType(Vec<EventRecord>):: decodeU8a: failed at 0x02090c7b4fcd4c00… on :  
{\"phase\":\"Phase\",\"event\":\"Event\",\"topics\":\"Vec<Hash>\"}:: decodeU8a: failed at 0x090c7b4fcd4c0041…  
on event:  {\"index\":\"EventId\",\"data\":\"Null\"}:: findMetaEvent: Unable to find Event with index 0x090c/[9,12]\n at.    createTypeUnsafe (<path>/index.js:44:915042)\n at createType (<path>/index.js:44:915233)\n at TypeRegistry.createType   (<path>/index.js:44:930949)\n at Scanner.getStorageValue (<path>/index.js:2:210356)\n at runMicrotasks   (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n at runNextTicks   (internal/process/task_queues.js:62:3)\n at processImmediate (internal/timers.js:434:9)\n at async Promise.all (index 0)\n   at async Scanner.getBlockDetail (<path>/index.js:2:206824)","timestamp":"2021-07-11 21:16:09","errorCode":1}  
```
```bash
error: 2436698-unknown createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index   0x0a00/[10,0] {"stack":"Error: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index   
0x0a00/[10,0]\n at createTypeUnsafe (<path>/index.js:44:915042)\n at createType (<path>/index.js:44:915233)\n at  
TypeRegistry.createType (<path>/index.js:44:930949)\n at Function._newFromValue (<path>/index.js:44:944119)\n at   
Function._decodeU8a (<path>/index.js:44:944779)\n at Function._decodeExtrinsic (<path>/index.js:44:944284)\n at new 
GenericExtrinsic (<path>/index.js:44:943933)\n at Scanner.decodeTx (<path>/index.js:2:210412)\n at  
<path>/index.js:2:207072\n at Array.map (<anonymous>)","timestamp":"2021-07-11 21:16:10","errorCode":1}  
```

- One thing that's common between the error blocks are that in all of them runtime code was updated, i.e `system.setCode(<code>)` call was dispatched. Here is the list of blocks where code updates happened: 
  -  `polkadot`: https://polkadot.subscan.io/event?module=system&event=codeupdated
  -  `kusama`: https://kusama.subscan.io/event?module=system&event=codeupdated&page=1&address=&startDate=&endDate=

- Updated runtime code means (not always) that `specVersion`, `metadata` and `type registry` of the runtime is also updated.

For this reason blocks where the runtime code was updated were not being decoded with the current block's metadata. This fix tries to decode the incoming raw value with the current block's chain info and if it fails it reverts the chain info one block number back.

This fixes the issue with code update blocks.

### CODE REVIEW

**Comment by ntduan** [comment]
Thanks for pointing that out. But I think using try catch also brings some new problems. Because it doesn't necessarily throw an error when the parsing is not working properly.

Because substrate uses the runtime of the previous block to execute the current block. So would it be simpler to change it to something like this here?

```
    const preblock = getPreBlock(blockHashOrBlockNumber)
    const runtimeVersion = await this.getRuntimeVersion(preblock);
```
https://github.com/open-web3-stack/open-web3.js/blob/master/packages/scanner/src/Scanner.ts#L214

**Comment by ntduan** [comment]
I took a look at the polkadot js code. It uses parentHash to get metadata and runtimeVersion. 
https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L152-L167

**Comment by dastanbeksamatov** [comment]
> I took a look at the polkadot js code. It uses parentHash to get metadata and runtimeVersion.
> https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L152-L167

that makes sense. I will refactor it to use metadata of a previous block

**Comment by dastanbeksamatov** [comment]
> Thanks for pointing that out. But I think using try catch also brings some new problems. Because it doesn't necessarily throw an error when the parsing is not working properly.
> 
> Because substrate uses the runtime of the previous block to execute the current block. So would it be simpler to change it to something like this here?
> 
> ```
>     const blockHash = getPreBlock(blockHashOrBlockNumber)
>     const runtimeVersion = await this.getRuntimeVersion(blockHash);
> ```
> 
> https://github.com/open-web3-stack/open-web3.js/blob/master/packages/scanner/src/Scanner.ts#L214

that was another suggestion I had - see: https://github.com/dastanbeksamatov/open-web3.js/blob/demo/packages/scanner/src/Scanner.ts#L213.

**Review by ntduan — APPROVED** [review]

**Pull request merged**
